[tool.poetry]
name = "complete-dbt-bootcamp-zero-to-hero"
version = "0.1.0"
description = ""
authors = ["yeha98555"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dbt-snowflake = "1.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
